CREATE TABLE IF NOT EXISTS distributed_lock
(
    id   BIGINT UNSIGNED AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL COMMENT '锁名称',
    PRIMARY KEY (id),
    UNIQUE KEY (name)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8
    COMMENT '分布式锁工具表';
